### ISSUE TITLE
文件用途提问

### ISSUE THREAD

**Issue by zsj527664** [Leopard-C/HttpServer#1]
你好，想请问一下，src目录下的三个lib_http_server开头的文件是起到什么作用的？

**Comment by Leopard-C** [comment]
项目根目录下的 `http_server.sln` 是`Visual Studio`软件的解决方案文件，`src`目录下的`lib_http_server.vcxproj`是该解决方案下的一个项目文件，用于编译静态库文件。

可以使用 `Visual Studio 2019` 及以上版本的软件打开 `http_server.sln`。

+ `http_server.sln`
  + `src/lib_http_server.vcxproj` 构建静态库
  + `example/example.vcxproj` 使用示例1
  + `example/example2.vcxproj` 使用示例2

**Comment by zsj527664** [comment]
非常感谢您的回答！除此之外我大概还有几个问题：
1. 另外想请问一下关于路由管理部分的实现是用于做什么的呢？是用于验证客户端发来的请求内容是否支持或者合法吗？
2. 有看到在Listener类种使用了strand，strand会将并发任务变成串行执行，这会不会影响响应效率？
3. 我查阅网上的资料了解到，acceptor对象的构造函数需要接收一个io_context对象，为什么在Listener的构造函数中使用了acceptor_(net::make_strand(*(svr->ioc_)))对acceptor_进行了初始化？

**Comment by zsj527664** [comment]
辛苦您有时间回答一下，非常感谢

**Comment by zsj527664** [comment]
关于第三点，我查看了相关的源码，发现acceptor的构造函数也可以接受一个executor，而make_strand会返回一个executor对象，我已经没有疑问，谢谢
